$ANSIBLE_VAULT;1.1;AES256
31316132663531313631626535336432316133316330383162383635643639616430316639363432
6137383233366164633232666138333765346530633363360a386136373639326333633633643331
64636566303430663131633434303236386566313830346134316432313039396166613466333931
6539613763636432630a633666643363646431383863646564366438393231666463383533653535
34376633643261633932353639353762343231376539353163656163663432653731633862343537
34363735636364313035663233383333616161346463316539633336626339323135623436333962
34313333363438393337653938653566643137646335663361333833636234336165646438383839
62356661653538653062633133666539656130303334313436353038343433613763663830393264
63353966616661303939393739663365393130316661306565386561666664633239
