---
- name: Create Users
  hosts: admin
  remote_user: root
  gather_facts: true
  roles:
    - hl.users

- name: Configure Admin Hosts
  hosts: admin
  become: true
  gather_facts: true
  roles:
    - hl.bind
...
